name: Release a plugin

on:
  workflow_call:

jobs:
  release:
    name: Release ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      -
        run: echo "${{ toJson(github) }}"
